# Project
version=6.1.0
java_version=25

# Metadata
mod_name=YungsExtras
mod_full_name=YUNG's Extras
mod_id=yungsextras
mod_author=YUNGNICKYOUNG
mod_description=Extra structures and vanilla+ content added throughout the game!
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.yungsextras
mc_version=26.3
mc_version_range=[26.3,)
mc_version_range_fabric=>=26.3
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
mc_version_neo_form=26.3-1

# CurseForge/Modrinth Publishing
cursegradle_version=1.1.24
compatible_versions=26.3
curseforge_project_id_fabric=590993
curseforge_project_id_neoforge=480006
modrinth_project_id=ZYgyPyfq
debug_publish=true

# Common
yungsapi_version=6.1.3

# Fabric
fabric_version=0.161.0
fabric_loader_version=0.19.5
clothconfig_version_fabric=26.3.158
modmenu_version_fabric=22.0.0-alpha.1

# NeoForge
neoforge_version=26.3.0.48-beta
neoforge_version_range=[26.3.0.48-beta,)
neoforge_loader_version_range=[4,)

# Credentials for publishing. Gets overwritten with global gradle.properties.
# Hands off, pal. This is for YUNG only.
curseforgeApiKey=""
modrinthToken=""

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
